# Generated by Django 4.0.3 on 2022-04-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congresso_app', '0002_cidade_estado_evento_palavrachave'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congresso_app.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='cep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='dataEHoraDeInicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e  hora de início'),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='evendoPrincipal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='logotipo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='palavrasChave',
            field=models.ManyToManyField(to='congresso_app.palavrachave'),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congresso_app.pessoa', verbose_name='Relizador'),
        ),
        migrations.AddField(
            model_name='evento',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='palavrachave',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='razaoSocial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
