# Generated by Django 4.0.3 on 2022-04-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congresso_app', '0004_eventocientifico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='congresso_app.pessoa')),
                ('curriculo', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            bases=('congresso_app.pessoa',),
        ),
        migrations.AlterField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congresso_app.pessoa', verbose_name='Relizador'),
        ),
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congresso_app.eventocientifico', verbose_name='Evento')),
            ],
        ),
    ]
