# Generated by Django 4.0.3 on 2022-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congresso_app', '0007_rename_evendoprincipal_evento_eventoprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigocientifico',
            name='autores',
            field=models.ManyToManyField(blank=True, to='congresso_app.autor'),
        ),
    ]
